# Generated by Django 4.0.6 on 2022-07-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Mundiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='interprete',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
