# Generated by Django 4.0.6 on 2022-08-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Mundiales', '0002_alter_cancion_interprete_alter_cancion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estadio',
            name='capacidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estadio',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
